# Triggers are used to determine when this pipeline is run
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
   include:
     - 'azure-pipelines.yml'
     - 'src/Ajax/**/*'
     - 'src/Blazor/**/*'
     - 'src/Console/**/*'

jobs:

# *************************************************************** #
# ******** EXAMPLE 1 - CONSOLE (.NET 6) ******** #
# *************************************************************** #

- job: BuildConsoleApp
  pool:
    vmImage: 'windows-2022'

  variables:
  - group: KeyVaultVariables
  - name: consoleNugetConfigPath
    value: 'src/nuget.config'
  - name: consoleProjectPath
    value: 'src/Console/MyDocProcApp/MyDocProcApp.csproj'
  - name: buildConfiguration
    value: 'Debug'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'

  # Restore the NuGet packges using Service connection for credentials
  - task: DotNetCoreCLI@2
    displayName: 'NuGet restore MyDocProcApp'
    inputs:
      command: 'restore'
      projects: $(consoleProjectPath)
      feedsToUse: 'config'
      nugetConfigPath: $(consoleNugetConfigPath)
      externalFeedCredentials: 'TelerikFeed'

  # Build the project
  - task: DotNetCoreCLI@2
    displayName: 'Build MyDocProcApp'
    inputs:
      command: 'build'
      projects: $(consoleProjectPath)
      configuration: $(buildConfiguration)

# *************************************************************** #
# ******* EXAMPLE 2 - ASP.NET AJAX (.NET Framework) ************* #
# *************************************************************** #
- job: BuildWebformsApp
  pool:
    vmImage: 'windows-2022'

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet '

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: 'src\Ajax\MySite.sln'
      feedsToUse: config
      nugetConfigPath: src/nuget.config
      externalFeedCredentials: TelerikFeed

  - task: MSBuild@1
    displayName: 'Build solution src\Ajax\MySite.sln'
    inputs:
      solution: 'src\Ajax\MySite.sln'
      platform: Any CPU
      configuration: Release

# ******************************************************* #
# ************* EXAMPLE 3 - BLAZOR (.NET 6) ************* #
# ******************************************************* #
- job: BuildBlazorApp
  pool:
    vmImage: 'windows-2022'

  variables:
# secrets from AzureKeyValue
  - group: KeyVaultVariables 
# local vars
  - name: nugetConfigPath
    value: 'src/nuget.config'
  - name: blazorProjectPath
    value: 'src/Blazor/MyBlazorApp.csproj'
  - name: buildConfiguration
    value: 'Debug'
  - name: rid
    value: any
  
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
  
  # ***** Step 1. Restore NuGet packages ***** #

  # [Option 1 - Use 'dotnet nuget update source'] 
  # ---------------------------------------------
  # This example uses Azure KeyVault secrets via the linked variable group 'KeyVaultVariables'.
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Update a package source in the nuget.config with the update source command (these variables are linked Azure KeyVault secrets)
        dotnet nuget update source Telerik --source https://nuget.telerik.com/v3/index.json --username '$(MYTELERIKACCOUNTUSERNAME)' --password '$(MYTELERIKACCOUNTPASSWORD)' --store-password-in-clear-text --configfile $(nugetConfigPath)
        # Restore packages
        dotnet restore $(blazorProjectPath) --configfile $(nugetConfigPath) --runtime $(rid)


  # [Option 2 - Use 'dotnet restore' with env variables ]
  # -----------------------------------------------------
  # - task: PowerShell@2
  #   displayName: 'Restore NuGet Packages'
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       # Copy the secret's value into the env var defined in your nuget.config.
  #       $env:TELERIK_USERNAME = '$(MY_TELERIK_EMAIL)'
  #       $env:TELERIK_PASSWORD ='$(MY_TELERIK_PASSWORD)'

  #       # Use the nuget.config to restore the packages.
  #       dotnet restore $(blazorProjectPath) --configfile $(nugetConfigPath) --runtime $(rid)


  # ***** Step 2. Build the project ***** #

  - task: DotNetCoreCLI@2
    displayName: 'Build Blazor Project'
    inputs:
      command: 'build'
      projects: $(blazorProjectPath)
      configuration: $(buildConfiguration)
