trigger:
  branches:
    include:
    - main
  paths:
   include:
     - 'azure-pipelines.yml'
     - 'src/Kendo/angular_demo/**/*'
     - 'src/Console/**/*'
     - 'src/Ajax/**/*'
     - 'src/Blazor/**/*'
     - 'src/AspNetCore/**/*'

variables:
  DOTNET_SDK_VERSION: '9.0.x'
  buildConfiguration: 'Release'
  nugetConfigPath: 'src/nuget.config'
  consoleProjectPath: 'src/Console/MyDocProcApp/MyDocProcApp.csproj'
  ajaxProjectPath: 'src/Ajax/MySite.sln'
  blazorProjectPath: 'src/Blazor/MyBlazorApp.sln'
  aspnetProjectPath: 'src/AspNetCore/MyAspNetCoreApp.sln'
# The following are saved as secret pipeline variables (in online AzDO editor)
# AKEYLESS_ACCESS_ID
# MY_TELERIK_NUGET_KEY
# MY_TELERIK_LICENSE_KEY

jobs:
# *************************************************************** #
# *                 EXAMPLE - KENDO ANGULAR                     * #
# *                                                             * #
# *                - Uses pipeline secrets -                    * #
# *************************************************************** #
- job: BuildAngularApp
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - powershell: |
      # Move to the angular project
      cd src\Kendo\angular_demo

      # Clear the angular cache, it may hold outdated key value
      rm -rf .angular/cache

      # Just incase the project doesnt have it installed yet, add the licensing package now
      npm install --save @progress/kendo-licensing;

      # Active the license
      npx kendo-ui-license activate

      # build the project
      npm run build
    displayName: "clean angular cache"
    env:
      TELERIK_LICENSE: $(MY_TELERIK_LICENSE_KEY)  # AzDO pipeline secret variable


# *************************************************************** #
# *                      EXAMPLE - CONSOLE                      * #
# *                                                             * #
# *                 - Uses Akeyless secrets -                   * #
# *************************************************************** #
- job: BuildConsoleApp
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # Get an authentication token from Azure so we can authenticate with Akeyless
  - task: AzureCLI@2
    name: 'AzureCLI'
    displayName: 'Get JWT from Azure Service Principal'
    inputs:
      azureSubscription: 'Azure MSA Account'
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $JWT=$(az account get-access-token --query accessToken --output tsv)
        echo "##vso[task.setvariable variable=azure_jwt;isoutput=true;issecret=true]$JWT"
  
  # Uses LanceMcCarthy/akeyless-extension-azdo to pull down static secret (also works for dynamic secrets)
  # Needs a JWT see https://github.com/LanceMcCarthy/akeyless-extension-azdo/blob/main/docs/getting-started.md
  - task: akeyless-secrets@1
    name: 'Akeyless1'
    displayName: 'Get Secrets from Akeyless'
    inputs:
      accessid: '$(AKEYLESS_ACCESS_ID)' # Stored as pipeline variable
      azureJwt: '$(AzureCLI.azure_jwt)' # Output variable fomr the previous step
      staticSecrets: '{"/personal-keys/mccarthy/TELERIK_NUGET_KEY":"NUGET_KEY"}'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: $(DOTNET_SDK_VERSION)

  - powershell: dotnet nuget update source 'Telerik_v3_Feed' --source 'https://nuget.telerik.com/v3/index.json' --username 'api-key' --password '$(Akeyless1.NUGET_KEY)' --configfile $(nugetConfigPath) --store-password-in-clear-text
    displayName: 'Update package source credentials'
  
  - powershell: dotnet restore $(consoleProjectPath) --configfile $(nugetConfigPath)
    displayName: 'restore packages'
  
  - powershell: dotnet publish $(consoleProjectPath) -o /app/publish /p:UseAppHost=false --no-restore
    displayName: 'Publish the project'
    env:
      TELERIK_LICENSE: $(MY_TELERIK_LICENSE_KEY) # AzDO pipeline secret variable


# *************************************************************** #
# *                     EXAMPLE - CONSOLE                       * #
# *                                                             * #
# *                - Uses Service connection -                  * #
# *************************************************************** #
- job: BuildConsoleApp
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: $(DOTNET_SDK_VERSION)

  # Using Service connection for credentials
  - task: DotNetCoreCLI@2
    displayName: 'NuGet restore MyDocProcApp'
    inputs:
      command: 'restore'
      projects: $(consoleProjectPath)
      feedsToUse: 'config'
      nugetConfigPath: $(nugetConfigPath)
      externalFeedCredentials: 'Telerik_v3'

  # Build the project
  - task: DotNetCoreCLI@2
    displayName: 'Build MyDocProcApp'
    inputs:
      command: 'build'
      projects: $(consoleProjectPath)
      configuration: $(buildConfiguration)
    env:
      TELERIK_LICENSE: $(MY_TELERIK_LICENSE_KEY) # AzDO pipeline secret variable


# ************************************************************* #
# *                   EXAMPLE - BLAZOR                        * #
# *                                                           * #
# *            - Uses Azure KeyVault secrets -                * #
# ************************************************************* #
- job: BuildBlazorApp
  pool:
    vmImage: 'ubuntu-latest'
  variables:
  - group: KeyVaultVariables
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: $(DOTNET_SDK_VERSION)

  - powershell: dotnet nuget update source 'Telerik_v3_Feed' -s 'https://nuget.telerik.com/v3/index.json' -u 'api-key' -p '$(TELERIK-NUGET-KEY)' --store-password-in-clear-text --configfile $(nugetConfigPath)
    displayName: 'Update Package Source Credentials'

  - powershell: dotnet restore $(blazorProjectPath) --configfile $(nugetConfigPath)
    displayName: 'Restore NuGet Packages'

  - powershell: dotnet publish $(blazorProjectPath) -o /app/publish /p:UseAppHost=false --self-contained false --no-restore
    displayName: 'Publish the project'
    env:
      TELERIK_LICENSE: $(TELERIK-LICENSE-KEY)  # Azure keyvault secret
 

# ************************************************************* #
# *                  EXAMPLE - ASPNET Core                    * #
# *                                                           * #
# *            - Uses Azure KeyVault secrets -                * #
# ************************************************************* #
- job: BuildBlazorApp
  pool:
    vmImage: 'ubuntu-latest'
  variables:
  - group: KeyVaultVariables # this supplies two secrets from Azure KeyVault; TELERIK-NUGET-KEY and TELERIK-LICENSE-KEY
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: $(DOTNET_SDK_VERSION)

  # SPECIAL - Instead of using a custom provided nuget.config, we simply add a new package source (which updates the default nuget.config)
  - powershell: dotnet nuget add source 'https://nuget.telerik.com/v3/index.json' -n 'Telerik_Dynamically_Added' -u 'api-key' -p '$(TELERIK-NUGET-KEY)' --store-password-in-clear-text
    displayName: 'Update Package Source Credentials'

  - powershell: dotnet restore $(aspnetProjectPath)
    displayName: 'Restore NuGet Packages'

  - powershell: dotnet publish $(aspnetProjectPath) -o /app/publish /p:UseAppHost=false --self-contained false --no-restore
    displayName: 'Publish the project'
    env:
      TELERIK_LICENSE: $(TELERIK-LICENSE-KEY)  # Azure keyvault secret


# *************************************************************** #
# *           EXAMPLE - ASP.NET AJAX (.NET Framework)           * #
# *                                                             * #
# *                 - Uses pipeline secrets -                   * #
# *************************************************************** #
- job: BuildWebformsApp
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet '

  # Step 1. Using nuget.exe, set the credentials of the 'Telerik' source in the nuget.config (using pipeline secrets)
  - task: PowerShell@2
    displayName: 'Update Package Source Credentials'
    inputs:
      targetType: 'inline'
      script: nuget sources update -Name 'Telerik_v3_Feed' -Source 'https://nuget.telerik.com/v3/index.json' -Username 'api-key' -Password '$(MY_TELERIK_NUGET_KEY)' -ConfigFile '$(nugetConfigPath)' -StorePasswordInClearText

  # Step 2. Using nuget.exe, restore the NuGet packages
  - task: PowerShell@2
    displayName: 'Restore NuGet Packages'
    inputs:
      targetType: 'inline'
      script: nuget restore '$(ajaxProjectPath)' -ConfigFile '$(nugetConfigPath)'

  # Step 3. Build the project without restoring packages automatically
  - task: MSBuild@1
    displayName: 'Build AJAX Project'
    inputs:
      solution: '$(ajaxProjectPath)'
      platform: Any CPU
      configuration: Release
      msbuildArguments: '/p:RestorePackages=false'
    env:
      TELERIK_LICENSE: $(MY_TELERIK_LICENSE_KEY) # AzDO pipeline secret variable
