trigger:
  branches:
    include:
    - main
  paths:
   include:
     - 'azure-pipelines.yml'
     - 'src/Kendo/angular_demo/**/*'
     - 'src/Console/**/*'
     - 'src/Ajax/**/*'
     - 'src/Blazor/**/*'
     - 'src/AspNetCore/**/*'
     - 'src/WinUI/**/*'
     - 'src/MAUI/**/*'
     - 'src/Wpf/**/*'
     - 'src/WinForms/**/*'

variables:
  DOTNET_SDK_VERSION: '10.0.x'
  buildConfiguration: 'Release'
  nugetConfigPath: 'src/NuGet.Config'
  # These pipeline secret veriables have been set using the AzDO yaml editor at dev.azure.com.
  # AKEYLESS_ACCESS_ID
  # MY_TELERIK_NUGET_KEY
  # DEPLOYMENT_KEY_FOR_XXXXXX

stages:
- stage: NodeBuilds
  displayName: 'Angular projects'
  jobs:
  # **************** KENDO ANGULAR (env) **************** #
  - job: BuildAngularAppWithVariables
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - powershell: |
        # ------ 1. Clean the angular cache, to avoid using any expired keys
        rm -rf .angular/cache
        # ------ 2. Install your project dependencies (add --save @progress/kendo-licensing; if missing from package.json)
        npm install
        # ------ 3. Activate
        npx kendo-ui-license activate
        # ------ 4. Build the project
        npm run build
      displayName: "Install Dependencies and Activate Kendo"
      workingDirectory: "src/Kendo/angular_demo"
      env:
        TELERIK_LICENSE: $(DEPLOYMENT_KEY_FOR_ANGULAR)

# ---------------------------------------------------------------------------- #

- stage: ConsoleBuilds
  displayName: 'Console projects'
  dependsOn: []
  jobs:

  # **************** CONSOLE (normal and akeyless matrix) **************** #

  - job: BuildConsoleApp
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      projectPath: 'src/Console/MyDocProcApp/MyDocProcApp.csproj'
    strategy:
      matrix:
        normal:
          name: 'Console Using Pipeline Secret Variable'
          deploymentKey: $(DEPLOYMENT_KEY_FOR_BLAZOR_AND_REPORTING)
        akeyless:
          name: 'Console Using Akeyless Secret'
          deploymentKey: $(Akeyless1.TK_DEPLOYMENT_KEY)
      maxParallel: 2
    steps:
    - task: AzureCLI@2
      displayName: 'Get JWT from Azure Service Principal'
      name: 'AzureCLI'
      # Auth token available in 'azure_jwt' output variable
      inputs:
        azureSubscription: 'Azure MSA Account'
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          $JWT=$(az account get-access-token --query accessToken --output tsv)
          echo "##vso[task.setvariable variable=azure_jwt;isoutput=true;issecret=true]$JWT"
      condition: eq(variables['strategyName'], 'akeyless')

    - task: akeyless-secrets@1 # Getting started https://github.com/LanceMcCarthy/akeyless-extension-azdo/blob/main/docs/getting-started.md
      name: 'Akeyless1'
      displayName: 'Get Secrets from Akeyless'
      inputs:
        accessid: 'p-sxfgaph9urt4om'
        azureJwt: '$(AzureCLI.azure_jwt)'
        staticSecrets: '{"/progress/DEPLOYMENT_KEY_FOR_BLAZOR_AND_REPORTING":"TK_DEPLOYMENT_KEY"}'
      condition: eq(variables['strategyName'], 'akeyless')

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(DOTNET_SDK_VERSION)

    - powershell: rm $(nugetConfigPath)
      displayName: 'Delete nuget.config, DPL packages are on nuget.org now'

    - powershell: dotnet publish $(projectPath) -o /app/publish /p:UseAppHost=false --no-restore
      displayName: 'Build and Publish'
      env:
        TELERIK_LICENSE: $(deploymentKey)


# ---------------------------------------------------------------------------- #

- stage: WebBuilds
  displayName: '.NET Web projects'
  dependsOn: [] 
  jobs:
  # **************** BLAZOR **************** #
  - job: BuildBlazorApp
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      projectPath: 'src/Blazor/MyBlazorApp.sln'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(DOTNET_SDK_VERSION)

    - powershell: rm $(nugetConfigPath)
      displayName: 'Delete nuget.config, packages are on nuget.org now'

    - powershell: dotnet restore $(projectPath)
      displayName: 'Restore NuGet Packages'

    - powershell: dotnet build $(projectPath)
      displayName: 'Build and publish'
      env:
        TELERIK_LICENSE: $(DEPLOYMENT_KEY_FOR_BLAZOR_AND_REPORTING)

  # **************** ASPNET Core **************** #

  - job: BuildAspNetCoreApp
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      projectPath: 'src/AspNetCore/MyAspNetCoreApp.sln'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(DOTNET_SDK_VERSION)

    - powershell: dotnet nuget update source 'Telerik_v3_Feed' -s 'https://nuget.telerik.com/v3/index.json' -u 'api-key' -p '$(MY_TELERIK_NUGET_KEY)' --store-password-in-clear-text --configfile $(nugetConfigPath)
      displayName: 'Update Package Source Credentials'

    - powershell: dotnet restore $(projectPath) --configfile $(nugetConfigPath)
      displayName: 'Restore NuGet Packages'
      
    - powershell: dotnet build $(projectPath) --no-restore
      displayName: 'Build the project'
      env:
        TELERIK_LICENSE: $(DEPLOYMENT_KEY_FOR_ASPNETCORE_AND_REPORTING)

  # **************** ASP.NET AJAX (SecureFile) **************** #

  - job: BuildAjaxApp
    pool:
      vmImage: 'windows-latest'
    variables:
      projectPath: 'src/Ajax/MySite.sln'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet.exe'
      inputs:
        versionSpec: '5.x'

    # NuGet Auth - Option 1
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: $(projectPath)
        feedsToUse: config
        nugetConfigPath: $(nugetConfigPath)
        externalFeedCredentials: 'Telerik_v3'

    # NuGet Auth - Option 2
    # You could also use nuget.exe's update command to set the credentials of the 'Telerik_v3_Feed' source defined in the nuget.config
    # - task: PowerShell@2
    #   displayName: 'Set Package Source Credentials'
    #   inputs:
    #     targetType: 'inline'
    #     script: nuget sources update -Name 'Telerik_v3_Feed' -Source 'https://nuget.telerik.com/v3/index.json' -Username 'api-key' -Password '$(MY_TELERIK_NUGET_KEY)' -ConfigFile '$(nugetConfigPath)' -StorePasswordInClearText

    - task: MSBuild@1
      displayName: 'Build AJAX Project'
      inputs:
        solution: '$(ajaxProjectPath)'
        platform: Any CPU
        configuration: Release
        msbuildArguments: '/t:Restore /p:Configuration=Release /p:RuntimeIdentifier=any'
      env:
        TELERIK_LICENSE: $(DEPLOYMENT_KEY_FOR_AJAX)

# ---------------------------------------------------------------------------- #

- stage: DesktopMobileBuilds
  displayName: 'Desktop and Mobile projects'
  dependsOn: []
  jobs:
  # **************** WinUI **************** #
  - job: BuildWinUI
    pool:
      vmImage: 'windows-latest'
    variables:
      projectPath: 'src/WinUI/MyDemo.sln'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(DOTNET_SDK_VERSION)

    - powershell: dotnet nuget update source 'Telerik_v3_Feed' -s 'https://nuget.telerik.com/v3/index.json' -u 'api-key' -p '$(MY_TELERIK_NUGET_KEY)' --store-password-in-clear-text --configfile $(nugetConfigPath)
      displayName: 'Update Package Source Credentials'

    - powershell: dotnet restore $(projectPath) --configfile $(nugetConfigPath)
      displayName: 'Restore NuGet Packages'

    - powershell: dotnet msbuild $(projectPath) /t:Restore /p:Platform=x64 /p:Configuration=Release /p:RestorePackages=true /p:RestoreRIDs=true /p:RestoreProjectStyle=PackageReference
      displayName: 'Restore RIDs'

    - powershell: >
        dotnet msbuild $(projectPath)
        /p:Platform=x64
        /p:Configuration=Debug
        /p:AppxBundlePlatforms="x64|arm64"
        /p:UapAppxPackageBuildMode=CI
        /p:AppxBundle=Never
        /p:GenerateAppxPackageOnBuild=false
        /p:AppxPackageSigningEnabled=false
      displayName: 'Build and Create MSIX'
      env:
        TELERIK_LICENSE: $(MY_TELERIK_LICENSE_KEY)

  # **************** .NET MAUI **************** #
  # Runners https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  
  - job: BuildMauiApp
    variables:
      projectPath: 'src/MAUI/MauiDemo.csproj'
      xcodeVersion: '26.6'
    strategy:
      matrix:
        android:
          TFM: 'net10.0-android'
          imageName: 'windows-latest'
          buildCommand: 'dotnet build $(projectPath) -f $(TFM) -c Debug'
        windows:
          TFM: 'net10.0-windows10.0.22621.0'
          imageName: 'windows-latest'
          buildCommand: 'dotnet build $(projectPath) -f $(TFM) -c Debug'
        ios:
          TFM: 'net10.0-ios'
          imageName: 'macOS-26'
          buildCommand: 'dotnet build $(projectPath) -f $(TFM) -c Debug -p:PublishTrimmed=True -p:MtouchLink=SdkOnly'
        maccatalyst:
          TFM: 'net10.0-maccatalyst'
          imageName: 'macOS-26'
          buildCommand: 'dotnet build $(projectPath) -f $(TFM) -c Debug -p:PublishTrimmed=True -p:MtouchLink=SdkOnly'
      maxParallel: 4
    pool:
      vmImage: $(imageName)
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(DOTNET_SDK_VERSION)

    - task: CmdLine@2
      displayName: 'Set Xcode to $(xcodeVersion)'
      inputs:
        script: |
          echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(xcodeVersion).app
          sudo xcode-select --switch /Applications/Xcode_$(xcodeVersion).app/Contents/Developer
      condition: or(eq(variables['strategyName'], 'ios'), eq(variables['strategyName'], 'maccatalyst'))

    - powershell: rm $(nugetConfigPath)
      displayName: 'Delete nuget.config, packages are on nuget.org now'

    - powershell: dotnet workload install maui
      displayName: 'Install maui workloads'
      
    - powershell: $(buildCommand)
      displayName: 'Build $(TFM)'
      env:
        TELERIK_LICENSE: $(DEPLOYMENT_KEY_FOR_MAUI)

  # **************** WPF & WinForms (matrix) **************** #

  - job: BuildWpfApp
    strategy:
      matrix:
        wpf:
          name: 'UI for WPF project'
          projectPath: 'src/Wpf/MyWpfApp/MyWpfApp.csproj'
          deploymentKey: $(DEPLOYMENT_KEY_FOR_WPF)
        winforms:
          name: 'UI for WinForms project'
          projectPath: 'src/WinForms/MyWinFormsApp/MyWinFormsApp.csproj'
          deplymentKey: $(DEPLOYMENT_KEY_FOR_WINFORMS)
      maxParallel: 2
    pool:
      vmImage: windows-latest
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: $(DOTNET_SDK_VERSION)

    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet.exe'
      inputs:
        versionSpec: '5.x'

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: $(projectPath)
        feedsToUse: config
        nugetConfigPath: $(nugetConfigPath)
        externalFeedCredentials: 'Telerik_v3'

    - task: MSBuild@1
      displayName: 'Build $(name)'
      inputs:
        solution: $(projectPath)
        platform: 'x64'
        configuration: 'Debug'
        msbuildArguments: '/p:RestorePackages=true /p:OutputPath=$(Build.artifactStagingDirectory)'
      env:
        TELERIK_LICENSE: $(deploymentKey)
