name: Build All Projects

on:
  push:
    branches: [ main ]

jobs:
  build_web:
    runs-on: ubuntu-latest
    
    env:
      RID: linux-x64 # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
      Configuration: Release
      DotNetVersionToUse: 3.1.302
      SolutionPath: src\Web\Web.sln
      NuGetConfigPath: src\Web\NuGet.Config
      TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
      TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: $env:DotNetVersionToUse

      - name: Restore NuGet Packages
        run: dotnet restore $env:SolutionPath --configfile $env:NuGetConfigPath --runtime $env:RID

      - name: Build Solution
        run: dotnet build $env:SolutionPath --configuration $env:Configuration --configfile $env:NuGetConfigPath --runtime $env:RID

  build_console:
    runs-on: macos-latest
    
    env:
      RID: any # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
      Configuration: Release
      DotNetVersionToUse: 3.1.302
      SolutionPath: src\Console\Console.sln
      NuGetConfigPath: src\Console\NuGet.Config
      TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
      TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: $env:DotNetVersionToUse
          config-file: src/Web/NuGet.Config
      
      - name: Restore NuGet Packages
        run: dotnet restore $env:SolutionPath --configfile $env:NuGetConfigPath --runtime $env:RID

      - name: Build Solution
        run: dotnet build $env:SolutionPath --configuration $env:Configuration --configfile $env:NuGetConfigPath --runtime $env:RID
  
  build_desktop:
    runs-on: windows-latest # WPF apps must be built on Windows runners
    
    env:
      RID: win-x86 # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
      Configuration: Release
      DotNetVersionToUse: 3.1.302
      SolutionPath: src\Wpf\Wpf.sln
      NuGetConfigPath: src\Wpf\NuGet.Config
      TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
      TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: $env:DotNetVersionToUse
          config-file: $env:NuGetConfigPath

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.1
      
      - name: Restore NuGet Packages
        run: dotnet restore $env:SolutionPath --configfile $env:NuGetConfigPath --runtime $env:RID

      - name: Build Solution
        run: dotnet build $env:SolutionPath --configuration $env:Configuration --configfile $env:NuGetConfigPath --runtime $env:RID

