name: MAUI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/MAUI/**/*'
      - '.github/workflows/main_build-maui.yml' 

env:
  TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}
  PROJECT_PATH: "src/MAUI/MauiDemo.csproj"
  DOTNET_VERSION: 10.0.x
  XCODE_VERSION: '26.6'
  JAVA_SDK_VERSION: '11'

jobs:
  maui-smoketest:
    name: "🧪 .NET MAUI Smoketest (${{matrix.name}})"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Android"
            os: windows-latest
            tfm: "net10.0-android"
          - name: "WinUI"
            os: windows-latest
            tfm: "net10.0-windows10.0.22621.0"
          - name: "iOS"
            os: macos-26
            tfm: "net10.0-ios"
          - name: "MacCatalyst"
            os: macos-26
            tfm: "net10.0-maccatalyst"
    steps:
    - name: "⬇️ Checkout"
      uses: actions/checkout@v7

    # Telerik.UI.for.Maui is available on nuget.org, so we can remove the telerik nuget server
    - name: "🧹 Remove extra NuGet.Config"
      shell: pwsh
      run: Remove-Item src/NuGet.Config

    - name: "🧰 Setup .NET Core SDK"
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    # Only needed for WinUI builds
    - name: "➕ Add msbuild to PATH"
      if: matrix.name == 'WinUI'
      uses: microsoft/setup-msbuild@v3

    - name: "☕ Set up Java SDK"
      uses: actions/setup-java@v5
      if: matrix.name == 'Android'
      with:
        distribution: 'microsoft'
        java-version: ${{env.JAVA_SDK_VERSION}}

    - name: "🍎 Set up Xcode"
      uses: maxim-lobanov/setup-xcode@v1
      if: matrix.name == 'iOS' || matrix.name == 'MacCatalyst'
      with:
        xcode-version: ${{env.XCODE_VERSION}}

    - name: "📦 Install MAUI workloads"
      run: dotnet workload install maui

    - name: "🧾 Create build args"
      id: arg-builder
      shell: pwsh
      run: |
        $buildArgs = @(
          '${{env.PROJECT_PATH}}'
          '-c', 'Debug'
          '-f', '${{matrix.tfm}}'
        )

        if ('${{matrix.name}}' -in @('iOS', 'MacCatalyst')) {
          $buildArgs += @(
            '-p:PublishTrimmed=True'
            '-p:MtouchLink=SdkOnly'
          )
        }

        "args=$($buildArgs -join ' ')" >> $env:GITHUB_OUTPUT

    - name: "🔨 Build project"
      run: dotnet build ${{steps.arg-builder.outputs.args}}
