name: Build Angular Application

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "angular/*"
    paths:
      - 'src/Kendo/angular_demo/**/*' 
      - '.github/workflows/main_build-angular.yml'

jobs:
  build_angular:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install NPM modules
      working-directory: src/Kendo/angular_demo
      run: npm install
    
    # The value of KENDO_LICENSE_KEY is stored as a GitHub repo secret (Settings -> Secrets -> Actions)
    # Get your key here https://www.telerik.com/kendo-angular-ui/components/my-license/#toc-download-your-license-key
    - name: Activate Kendo UI License
      working-directory: src/Kendo/angular_demo
      run: npx kendo-ui-license activate
      env:
        KENDO_UI_LICENSE: ${{ secrets.KENDO_LICENSE_KEY }}

    - name: Build
      working-directory: src/Kendo/angular_demo
      run: npm run build --prod

    - uses: actions/upload-artifact@v4
      with:
        name: "Kendo UI Test"
        path: 'src/Kendo/angular_demo/'
        if-no-files-found: error
        retention-days: 1