name: Build WinForms Application

on:
  push:
    branches:
      - main
    paths:
      - 'src/WinForms/**/*'
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  # A job that builds a .NET Framework WPF application using Telerik UI for WinForms
  build_desktop:
    runs-on: windows-latest # WinForms apps must be built on Windows runners
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
    
    # We use the dotnet CLI (instead of nuget.exe) to restore the nuget packages before using msbuild
    - name: NuGet Restore
      run: dotnet restore src\WinForms\MyWinFormsApp\MyWinFormsApp\MyWinFormsApp.csproj --configfile src\NuGet.Config --runtime win-x86
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    # Use msbuild to compile the .NET Framework WinForms project
    - name: Build the WinForms application 
      run: msbuild src\WinForms\MyWinFormsApp\MyWinFormsApp\MyWinFormsApp.csproj /t:Restore /p:Configuration=Release /p:RuntimeIdentifier=win-x86
