name: Angular

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "angular/*"
    paths:
      - 'src/Kendo/angular_demo/**/*' 
      - '.github/workflows/main_build-angular.yml'

jobs:
  build_angular:
    runs-on: ubuntu-latest
    env:
      TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install NPM modules
      working-directory: src/Kendo/angular_demo
      run: npm install
    
    - name: Activate Kendo UI License
      working-directory: src/Kendo/angular_demo
      run: npx kendo-ui-license activate

    - name: Build
      working-directory: src/Kendo/angular_demo
      run: npm run build --prod
