name: Angular

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "angular/*"
    paths:
      - 'src/Kendo/angular_demo/**/*' 
      - '.github/workflows/main_build-angular.yml'

jobs:
  build_angular:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install NPM modules
      working-directory: src/Kendo/angular_demo
      run: |
        # 1. Clean the angular cache, to avoid using any expired keys
        rm -rf .angular/cache

        # 2. Install your project dependencies
        npm install
        # npm install --save @progress/kendo-licensing;  # if missing from package.json

        #3. Activate
        npx kendo-ui-license activate

        #4. Build the project
        npm run build  --prod
    env:
      TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}
