name: Build UWP Application

on:
  push:
    branches:
      - main
    paths:
      - 'src/Uwp/**/*'
      - '.github/workflows/main_build-uwp.yml' 

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
      
    - name: NuGet Restore - Class Library Project
      run: nuget restore src\Uwp\SalesDashboard.UWP.sln -ConfigFile src\nuget.config
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}  

    - name: NuGet Restore - Platform Project
      run: nuget restore src\Uwp\SalesDashboard.UWP.sln -ConfigFile src\nuget.config
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}  
    
    - name: Build UWP Project
      run: msbuild src\Uwp\SalesDashboard.UWP.sln /p:Platform=x64 /p:Configuration=Debug /p:AppxPackageSigningEnabled=false
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: UWP Artifacts
        path: src\Uwp\SalesDashboard.UWP\bin
