name: Console (.NET) - Artifactory Only

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build_console:
    name: "🔨 Build Console"
    runs-on: ubuntu-latest
    steps:
    - name: "⬇️ Checkout"
      uses: actions/checkout@v7

    - name: "🧰 Setup .NET SDK"
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'

    - name: "🧹 Remove dedicated NuGet.Config"
      run: rm src/NuGet.Config

    - name: "➕ Add JFrogArtifactory Package Source"
      run: |
        dotnet nuget add source "https://bed-artifactory.bedford.progress.com/artifactory/api/nuget/v3/dt-nuget-virtual-tierpoint/index.json" `
          --name "artifactory" `
          --username ${{secrets.ARTIFACTORY_NUGET_USERNAME}} `
          --password ${{secrets.ARTIFACTORY_NUGET_PASSWORD}} `
          --store-password-in-clear-text

    - name: "🔨 Build Project"
      run: dotnet build "src/Console/MyDocProcApp/MyDocProcApp.csproj"
      env:
        TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}