name: Console using Artifactory (.NET)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "console/*"
    paths:
      - 'src/Console/**/*'
      - '.github/workflows/main_build-console.yml' 

jobs:
  build_console:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build using only an Artifactory virtual NuGet source
      shell: pwsh
      run: |
        # Remove all existing sources
        dotnet nuget list source | ForEach-Object { 
          dotnet nuget remove source -n $_.Name 
        }

        # Add the Artifactory virtual source
        dotnet nuget add source "artifactory_virtual" \
          -s ${{env.ARTIFACORY_URL}} \
          -u ${{env.ARTIFACORY_USER}} \
          -p ${{env.ARTIFACORY_PWD}} \
          --store-password-in-clear-text
        
        # Build the project to restore the packages
        dotnet build ${{env.PROJECT_PATH}}
      env:
        PROJECT_PATH: "src/Console/MyDocProcApp/MyDocProcApp.csproj"
        ARTIFACORY_URL: "https://bed-artifactory.bedford.progress.com/artifactory/api/nuget/v3/dt-nuget-virtual-tierpoint/index.json"
        ARTIFACORY_USER: ${{secrets.ARTIFACTORY_NUGET_USERNAME}}
        ARTIFACORY_PWD: ${{secrets.ARTIFACTORY_NUGET_PASSWORD}}
        TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}
