# This example shows you how ot use Akeyless to fetch the required secrets instead of GitHub Actions secrets
name: Console (.NET)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "console/*"
    paths:
      - 'src/Console/**/*'
      - '.github/workflows/main_build-console.yml' 

jobs:
  build_console:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux, win]
        config: [x64, arm64]
    env:
      CSPROJ_PATH: src/Console/MyDocProcApp/MyDocProcApp.csproj
      NUGETCONFIG_PATH: src/NuGet.Config
      BUILD_CONFIGURATION: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Remove dedicated NuGet.Config
      run: rm src/NuGet.Config

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: '10.0.x'

    - name: Build project
      run: dotnet build ${{env.CSPROJ_PATH}} --configuration ${{env.BUILD_CONFIGURATION}} --runtime ${{matrix.os}}-${{matrix.config}}
      env:
        TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}
