# For docker publish example, see: main_docker.yml
name: Blazor (with Reporting)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "blazor/*"
    paths:
      - 'src/Blazor/**/*'
      - '.github/workflows/main_build-blazor.yml'

env:
  CONFIGURATION: Release
  PROJ_PATH: src/Blazor/MyBlazorApp/MyBlazorApp.csproj
  DOTNET_VERSION: "10.0.x"

jobs:
  telerik_nuget:
    name: Telerik NuGet
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{env.DOTNET_VERSION}}

    - name: Restore NuGet Packages
      run: dotnet restore ${{env.PROJ_PATH}} --configfile src/NuGet.Config
      env:
        TELERIK_USERNAME: "api-key"
        TELERIK_PASSWORD: ${{secrets.TELERIK_NUGET_KEY}}

    - name: Build Test Project
      run: dotnet build ${{env.PROJ_PATH}} -c ${{env.CONFIGURATION}} --no-restore
      env:
        TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}

  # nuget_org:
  #   name: Public NuGet
  #   runs-on: ${{matrix.os}}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - os: ubuntu-latest
  #         - os: windows-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v6

  #   # Deleting the nuget.config to prove Telerik.UI.for.Blazor is on nuget.org
  #   - run: rm src/NuGet.Config

  #   - name: Setup .NET Core SDK
  #     uses: actions/setup-dotnet@v5
  #     with:
  #       dotnet-version: ${{env.DOTNET_VERSION}}

  #   - name: Build Test Project
  #     run: dotnet build ${{env.PROJ_PATH}} -c ${{env.CONFIGURATION}}
  #     env:
  #       TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}