name: Build UWP Application

on:
  push:
    branches:
      - main
    paths:
      - 'src/Uwp/**/*'
      - '.github/workflows/main_build-uwp.yml' 

env:
  TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }} # used by the NuGet.Config file
  TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }} # used by the NuGet.Config file

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        msbuild-architecture: x64
      
    - name: NuGet Restore - Class Library Project
      run: nuget restore src\Uwp\SalesDashboard.UWP.sln -ConfigFile src\nuget.config

    - name: NuGet Restore - Platform Project
      run: nuget restore src\Uwp\SalesDashboard.UWP.sln -ConfigFile src\nuget.config 
    
    - name: Build UWP Project
      run: msbuild src\Uwp\SalesDashboard.UWP.sln /p:Platform=x64 /p:Configuration=Debug /p:AppxPackageSigningEnabled=false
    
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: UWP Artifacts
    #     path: src\Uwp\SalesDashboard.UWP\bin
