name: Build WinForms Application

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "winforms/*"
    paths:
      - 'src/WinForms/**/*'
      - '.github/workflows/main_build-winforms.yml' 

jobs:
  # A job that builds a .NET Framework WPF application using Telerik UI for WinForms
  build_desktop:
    runs-on: windows-latest # WinForms apps must be built on Windows runners
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.2
    
    # We use the dotnet CLI (instead of nuget.exe) to restore the nuget packages before using msbuild
    - name: NuGet Restore
      run: dotnet restore src\WinForms\MyWinFormsApp\MyWinFormsApp.csproj --configfile src\NuGet.Config --runtime win-x86
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

    # Use msbuild to compile the .NET Framework WinForms project
    - name: Build the WinForms application 
      run: msbuild src\WinForms\MyWinFormsApp\MyWinFormsApp.csproj /t:Restore /p:Configuration=Release /p:RuntimeIdentifier=win-x86
