name: Console using Artifactory (.NET)

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build_console:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Use only Artifactory NuGet Source
      run: |
        # 1. remove all existing packages sources
        $sourceList = dotnet nuget list source
        $sourceNames = @()
        foreach ($line in $sourceList) {
            if ($line -match '^\s*\d+\.\s+(.*)\s+\[Enabled\]') {
                $sourceNames += $matches[1].Trim()
            }
        }
        foreach ($name in $sourceNames) {
            dotnet nuget remove source "$name"
            Write-Host "Removed $name ..."
        }

        # 2. Add Artifactory source
        dotnet nuget add source ${{secrets.ARTIFACTORY_NUGET_URL}} --name "artifactory_virtual" --username ${{secrets.ARTIFACTORY_NUGET_USERNAME}} --password ${{secrets.ARTIFACTORY_NUGET_PASSWORD}} --store-password-in-clear-text

    - name: Build Console App
      run: dotnet build "src/Console/MyDocProcApp/MyDocProcApp.csproj"
      env:
        TELERIK_LICENSE: ${{secrets.TELERIK_LICENSE_KEY}}
