name: Test ZAP Scan

on:
  workflow_dispatch:
    inputs:
      container_name:
        description: 'Container Name'
        required: false
        type: string
        default: 'lancemccarthy/aspnetcore-reporting-from-msftbase'
      port_internal:
        description: 'Internal Port'
        required: false
        type: string
        default: '8080'
      port_external:
        description: 'External Port'
        required: false
        type: string
        default: '8888'
      container_tag:
        description: 'Container Tag'
        required: false
        type: string
        default: 'latest'
  
jobs:
  build_spa:
    runs-on: ubuntu-latest
    name: Run App and ZAP scan
    steps:
    - name: Start ${{github.event.inputs.container_name}}
      run: docker run -d -p ${{github.event.inputs.port_external}}:${{github.event.inputs.port_internal}} ${{github.event.inputs.container_name}}:${{github.event.inputs.container_tag}}

   # START -TEMPORARY (ONLY NEEDED FOR THIS TEST WORKFLOW TO ACCESS THE OWASP ZAP ACTION)
    - name: Checkout private OWASP ZAP action
      uses: actions/checkout@v7
      with:
        repository: prgs-community/githubactions-reusableworkflows
        ref: main
        token: ${{secrets.CROSS_ORG_ACTIONS_PAT}}
        path: ./.github/private-actions/githubactions-reusableworkflows
    # END - TEMPORARY

    - name: Run OWASP ZAP scan
      uses: ./.github/private-actions/githubactions-reusableworkflows/actions/OWASP_ZAP
      with:
        ZAP_SCAN_URL: "http://localhost:${{github.event.inputs.port_external}}"
        ZAP_SQL_TESTING: SQL
        ZAP_TEST_COVERAGE: base
        PR_SUMMARY: true
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload ZAP scan artifact
      uses: actions/upload-artifact@v7
      with:
        name: zap-scan-results
        path: ${{github.workspace}}/zap-results/*
